# Generated by Django 3.0.4 on 2020-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='GraveKeeper',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='name',
            name='YearDate',
            field=models.CharField(default=2010, max_length=10),
            preserve_default=False,
        ),
    ]
